os: linux
dist: bionic
language: c

addons:
  apt:
    packages:
      - avr-libc
      - avrdude
      - binutils-arm-none-eabi
      - binutils-avr
      - build-essential
      - dfu-programmer
      - dfu-util
      - gcc
      - gcc-arm-none-eabi
      - gcc-avr
      - git
      - libnewlib-arm-none-eabi
      - software-properties-common
      - unzip
      - wget
      - zip

script:
  - git submodule update --init
  - make ergodash/rev1:s1061123 ergodox_ez:s1061123

before_deploy:
  - cp bintray.tmpl bintray.json
  - sed -i -e s%@DATE@%$(date +%Y-%m-%d)% bintray.json
  - sed -i -e s%@VERSION@%$(git rev-parse  --short HEAD)% bintray.json

deploy:
  - provider: bintray
    edge: true
    user: s1061123
    file: bintray.json
    key: $BINTRAY_API
    cleanup: false
    on:
      all_branches: true

after_deploy:
#- 'curl -X PUT -us1061123:$BINTRAY_API https://api.bintray.com/content/s1061123/generic/qmk_firmware/${TRAVIS_COMMIT::8}/ergodox.hex/publish'
#- 'curl -X PUT -us1061123:$BINTRAY_API https://api.bintray.com/content/s1061123/generic/qmk_firmware/${TRAVIS_COMMIT::8}/ergodash_rev1_s1061123.hex/publish'
  - sleep 30
  - 'curl -X PUT -H "Accept: application/json" -H "Content-type: application/json"  -us1061123:$BINTRAY_API https://api.bintray.com/file_metadata/s1061123/generic/${TRAVIS_COMMIT::8}/ergodash_rev1_s1061123.hex  -d "{\"list_in_downloads\":true}"'
  - 'curl -X PUT -H "Accept: application/json" -H "Content-type: application/json"  -us1061123:$BINTRAY_API https://api.bintray.com/file_metadata/s1061123/generic/${TRAVIS_COMMIT::8}/ergodox_ez_s1061123.hex  -d "{\"list_in_downloads\":true}"'
